# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_price',
            field=models.IntegerField(default='0'),
        ),
    ]
